name: GCC tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  testing:
    name: GCC ${{ matrix.gcc-version }} - openmpi
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gcc-version: [ '15' ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install GCC ${{ matrix.gcc-version }}
        uses: egor-tensin/setup-gcc@v2
        with:
          version: ${{ matrix.gcc-version }}

      - name: Check GCC version
        run: gcc --version

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.26.0

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          profile_detect: 'false'

      - name: Check Conan version
        run: conan --version

      - name: Generate Conan profile
        env:
          CXX: g++
          CC: gcc
        run: |
          conan profile detect --name=default

      - name: Set cpp version Conan profile
        run: |
          sed -i.bak -E 's|^(compiler\.cppstd\s*=\s*).*$|\1gnu20|' ~/.conan2/profiles/default || echo -e "[settings]\ncompiler.cppstd=gnu20" >> ~/.conan2/profiles/default

      - name: Check Conan profile
        run: cat ~/.conan2/profiles/default

      - name: Install OpenMPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: openmpi

      - name: OpenMPI version
        run: mpirun --version

      # The libscalapack-mpi-dev only works with OpenMPI. For MPICH support, check libscalapack-mpich-dev.
      # If added to the test matrix, consider using `if [ "${{ matrix.mpi }}" = "openmpi" ];` to differentiate
      # the cases.
      - name: Install ScaLAPACK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libscalapack-mpi-dev

      - name: Generate build directory
        run: mkdir -p build

      - name: Configure
        working-directory: build
        env:
          CXX: g++
          CC: gcc
        run: |
          cmake -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake ..

      - name: Compile
        working-directory: build
        run: cmake --build .
